name: Github Actionsで Firebaseに Build & Deploy
'on':
  push:
    branches:
      # - master
      - dev

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOKS }}

jobs:
  build_and_deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2

      - name: Nuxtアプリのビルド(環境変数設定含む)
        run: npm ci && npm run build
        env:
          # BASE_URL: ${{ secrets.BASE_URL }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

      - name: NuxtアプリをHostingへデプロイ
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project=${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


      - name: Slackに成功通知
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_ICON: https://i.gyazo.com/94757e237ec409db29cf5baccaba3182.png
          SLACK_USERNAME: Github Actions Bot
          SLACK_CHANNEL: firebase-notice
          SLACK_TITLE: Success Deploy
          SLACK_COLOR: good
          SLACK_MESSAGE: firebaseへのデプロイが成功しました

      - name: Slackに失敗通知
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_ICON: https://i.gyazo.com/94757e237ec409db29cf5baccaba3182.png
          SLACK_USERNAME: Github Actions Bot
          SLACK_CHANNEL: firebase-notice
          SLACK_TITLE: Failure Deploy
          SLACK_COLOR: danger
          SLACK_MESSAGE: firebaseへのデプロイが失敗しました
